var STORAGE_ACCOUNT_NAME = "nslconf";
var STORAGE_ACCOUNT_KEY = "sKE35CM2ymq4WtjZChZP/de94Qg4+hSVTjvhLnQoS4SPgJE0q2HI3KoH1p055es4fb/dH7LRh2xxCNN5/WsFFg==";

var constr="Server=tcp:whrqqmu9r0.database.windows.net,1433;Database=telvoy_db;User ID=tvadmin@whrqqmu9r0;Password=Admin123;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;";

var PULL_EMAIL_ID ="confme@ext.movial.com";
var PULL_EMAIL_PASS="aivohyiey0iePh";
var PULL_EMAIL_SERVER="imap.gmail.com";
var PULL_EMAIL_SERVER_PORT=993;
var PULL_EMAIL_SERVER_SECURE=true;
var PULL_EMAIL_DURATION=60*1000;
var NOTIFICATION_DURATION=60*1000;


exports.STORAGE_ACCOUNT_NAME = STORAGE_ACCOUNT_NAME;
exports.STORAGE_ACCOUNT_KEY = STORAGE_ACCOUNT_KEY;
exports.PULL_EMAIL_ID=PULL_EMAIL_ID;
exports.PULL_EMAIL_PASS=PULL_EMAIL_PASS;
exports.PULL_EMAIL_SERVER=PULL_EMAIL_SERVER;
exports.PULL_EMAIL_SERVER_PORT=PULL_EMAIL_SERVER_PORT;
exports.PULL_EMAIL_SERVER_SECURE=PULL_EMAIL_SERVER_SECURE;
exports.PULL_EMAIL_DURATION=PULL_EMAIL_DURATION;
exports.NOTIFICATION_DURATION=NOTIFICATION_DURATION;